### ISSUE TITLE
[feature request] sorted autocomplete

### ISSUE THREAD

**Issue by Fire69** [athombv/com.athom.soundboard#10]
Simple question.

Could you make the list of uploaded files alphabetical? Or sortable in some way?

I like a nice overview and when you remove and re-add files they end up at the bottom, instead of together with the other files they belong to (if you use a group of files, ex. my doorbell sounds)

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2621

**Comment by WeeJeWel** [comment]
Just type and the list will be filtered :)
