### ISSUE TITLE
Can't upload a mp3 File! Homey 2.0 IOS

### ISSUE THREAD

**Issue by Sillec123** [athombv/com.athom.soundboard#12]
My files are:
-Mono 
-22khz
Size 12 KB 

Please give us more information about the supported files!

**Comment by robertklep** [comment]
@weejewel [`getExtByType `](https://github.com/athombv/com.athom.soundboard/blob/e059194d9835e05c2e52cbdb61b3561936c8a4be/app.js#L140-L148) doesn't check for `audio/mpeg`.

**Comment by Sillec123** [comment]
What does it mean?

**Comment by robertklep** [comment]
It means I found the reason why you can't upload MP3 files from iOS, and am suggesting how to fix it.

**Comment by Sillec123** [comment]
The issue is independent of the os. Android app version with emulator got the same problem.

**Comment by robertklep** [comment]
Yes, the issue is with the app running on Homey, not with a specific OS.

**Comment by Sillec123** [comment]
But wav is also not working!!!

**Comment by WeeJeWel** [comment]
Can you guys attach the files that don't upload here? I can then fix the issue much easier.

**Comment by robertklep** [comment]
@WeeJeWel I can't, I was posting on behalf of someone else, but after they changed [line 141](https://github.com/athombv/com.athom.soundboard/blob/e059194d9835e05c2e52cbdb61b3561936c8a4be/app.js#L141) to:

    if ( type === 'audio/mp3' || type === 'audio/mpeg' )

it worked.

**Comment by Sillec123** [comment]
Yes, i tried different file types and frequencies.
[Archiv.zip](https://github.com/athombv/com.athom.soundboard/files/2763351/Archiv.zip)

**Comment by WeeJeWel** [comment]
Fixed in v2.0.4, now in beta!
