### ISSUE TITLE
Soundboard not working

### ISSUE THREAD

**Issue by sleutelsnet** [athombv/com.athom.soundboard#15]
Since December 2021 soundboard app is not working any more. When configuring the app, I can still see my mp3 files, but trying to play one of them yields the error:
"lame is not defined"

**Comment by hansallis** [comment]
+1 (same error message)

**Comment by WeeJeWel** [comment]
Thank you for reporting, we’ll release a fix as soon as possible.

**Comment by RobinBol** [comment]
Fixed in Homey Pro v7.2.1-rc.3 (just released as Experimental update).
