### ISSUE TITLE
[feature] Loop card?

### ISSUE THREAD

**Issue by Fire69** [athombv/com.athom.soundboard#2]
Would it be possible to make a card to loop a sound?  That would be handy to use in an alarm flow.
I use several cards with a delay now to play an sirene several times but that's not a very nice solution...

**Comment by WeeJeWel** [comment]
Cool suggestion! I'll look into it :)

**Comment by kukel** [comment]
But also make a card to stop playing a sound then... Alarms are not legally allowed to last forever iirc. Or allow it loop for x minutes

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2626

**Comment by WeeJeWel** [comment]
The app has no way to know when the sound is finished playing so this cannot be implemented.

You can always create a Flow to implement such behavior.

**Comment by kukel** [comment]
Wow... how can the app not know when the sound finished playing? It **IS**
playing the sound. Even my 3 year old nowshen a sound finished playing.
Homey and some of its ap[s get dumber and dumber...

Op di 22 jan. 2019 14:01 schreef Emile Nijssen <notifications@github.com:

**Comment by Fire69** [comment]
> Wow... how can the app not know when the sound finished playing?

I'm guessing the app just 'throws' the file to the audioplayer integrated in Homey and nothing more.
For example, when my doorbell is rang, the app plays an mp3.
When you push the button twice, the app plays the mp3 twice at the same time.

I have to admit, it's a bit disappointing, I opened a couple issues/feature request, they have all been rejected.
