### ISSUE TITLE
[feature request] Stop sounds currently playing

### ISSUE THREAD

**Issue by bm480** [athombv/com.athom.soundboard#5]
I use several cards to keep an alarm sound playing in a loop. The sound lasts for 25 seconds, it would be nice to be able to stop the sound when the alarm is turned off again. 

Right now I just mute the speaker by turning the volume to zero. But when an event that involves sound occurs within max. 25 seconds, the siren is still playing.

**Comment by WeeJeWel** [comment]
@jeroenvollenbrock This would need a ManagerAudio API call.

Not very high on our list, though.

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2624

**Comment by kevinhab** [comment]
> I use several cards to keep an alarm sound playing in a loop. The sound lasts for 25 seconds, it would be nice to be able to stop the sound when the alarm is turned off again.
> 
> Right now I just mute the speaker by turning the volume to zero. But when an event that involves sound occurs within max. 25 seconds, the siren is still playing.

I have the same. Very nice to have stop playing function

**Comment by WeeJeWel** [comment]
You can achieve this by playing the sound in a Flow, and running the Flow only when a certain variable is true.
