### ISSUE TITLE
[feature request] Being able to play sound to channel with which Homey interacts

### ISSUE THREAD

**Issue by bm480** [athombv/com.athom.soundboard#6]
I have a flow that triggers at speech input. I play a confirmation sound using soundboard, however this sound plays on Homey while I was using the iPhone app. Users near Homey are surprised to hear the sound while I can't hear it because I'm not with Homey...

**Comment by WeeJeWel** [comment]
I'm sorry, but playing sounds on an iPhone will not be supported.
