### ISSUE TITLE
Allow streaming local audio files directly from filesystem

### ISSUE THREAD

**Issue by matjaz** [athombv/com.athom.soundboard#7]
When I am in a process of creating/streaming file to filesystem it would be awesome if I could stream it directly, without requiring it to first upload it to Homey, as this app does.

Also I haven't found sdk 2 version of this functionality.

Please see https://github.com/matjaz/homey-youtube/issues/19#issuecomment-332421113

**Comment by WeeJeWel** [comment]
You can save the file in the userdata folder, which is accessible over http by default under http://homeyip/app/com.foo/userdata
