### ISSUE TITLE
[feature request] Global tag support

### ISSUE THREAD

**Issue by Fire69** [athombv/com.athom.soundboard#8]
Hi,

I think it would be nice to have tag support for this app.
Now you always have to explicitly select the file you want to play.
But it would be a nice feature if you could use tags to easily play different sounds with tags.

Example for my doorbell: https://forum.athom.com/discussion/3929/randomize-doorbell-sound
I could use <occasion><number> to randomize the sound at every press of the doorbell.

**Comment by WeeJeWel** [comment]
Homey knows no audio-tags (yet). You could use the random condition to randomize the sound using the then/else column.

**Comment by Fire69** [comment]
I've got it running with a BL card that fills a var with round(random(1,5)) for now, so it's OK.
But the tag support would still be nice :)

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2623

**Comment by WeeJeWel** [comment]
Won't fix.
