### ISSUE TITLE
[feature request] Set active speaker

### ISSUE THREAD

**Issue by MrReaL** [athombv/com.athom.soundboard#9]
In addition to the request "Soundboard to media" it would be really nice to stream sound to a speaker of my choice (Sonos or Heos speaker for example). I tried using the feature "Set active speaker" in an flow to Alarm me with sound upstairs. No luck.

**Comment by RobinBol** [comment]
Moved issue to main issue tracker: https://github.com/athombv/homey/issues/2622

**Comment by WeeJeWel** [comment]
Won't fix.

**Comment by MrReaL** [comment]
> Won't fix.

Why?
